name: Unity Project to .NET Solution Export
on:
  workflow_dispatch:
    inputs:
      repository:
        description: "GitHub repository name"
        required: true
        type: string
      branch:
        description: "Branch of the Unity project"
        required: true
        type: string
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: "refs/heads/${{inputs.branch}}"
          token: ${{ secrets.GH_PAT_TOKEN }}
          clean: false

      - name: Exclude Assets, Fetch Tool Script
        run: |
          TARGET_DIR="Assets"

          find "$TARGET_DIR" -type f ! -name "*.asmdef" ! -name "*.asmdef.meta" ! -name "dummy.cs"

          find "$TARGET_DIR" -name "*.asmdef" -exec dirname {} \; | while read -r dir;
            touch "$dir/dummy.cs"
          done

          find "$TARGET_DIR" -type d -empty -delete

          tree

          mkdir -p Assets/Editor
          curl -o Assets/Editor/DotnetGenerator.cs https://raw.githubusercontent.com/JacKooDesu/unity-but-dotnet-project/main/Tools/DotnetGenerator.cs

      - name: Compile and Exit
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          buildMethod: DotnetGenerator.Run
          customParameters: -batchmode -nographics
          allowDirtyBuild: true

      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: project
          path: ./exported/
